### ISSUE TITLE
Problem with addpath

### ISSUE THREAD

**Issue by nzjc** [dbarrosop/gobgp-controller#1]
Hi David, thanks very much for this work (nearly exactly 1 year on!)

When I attempt to follow your instructions, I get the following error when adding a path:

`root@ce5b416deb2d:/gobgprest#  python add_path.py 10.0.123.100 50051 2001:db8:666::/64 2001:db8:123::300 65000:1 110

Traceback (most recent call last):
  File "add_path.py", line 88, in <module>
    run(gobgp, port, prefix, nexthop, community, med)
  File "add_path.py", line 73, in run
    create_path(channel, prefix, nexthop, community, med)
  File "add_path.py", line 57, in create_path
    _call_grpc(channel, "AddPath", "AddPathRequest", **kwargs)
  File "add_path.py", line 17, in _call_grpc
    return api(request(**kwargs), _TIMEOUT_SECONDS)
  File "/usr/local/lib/python2.7/dist-packages/grpc/beta/_client_adaptations.py", line 309, in __call__
    self._request_serializer, self._response_deserializer)
  File "/usr/local/lib/python2.7/dist-packages/grpc/beta/_client_adaptations.py", line 195, in _blocking_unary_unary
    raise _abortion_error(rpc_error_call)
grpc.framework.interfaces.face.face.RemoteError: RemoteError(code=StatusCode.UNKNOWN, details="unknown route family. AFI: 0, SAFI: 0")`

This to me looks like the gobgp system is expecting the AFI/SAFI in a format other that what we're passing it with kwargs. I am not 100% sure, but perhaps it's expecting them as integers instead of combined via the bitwise operation you do on them in Python. I am very naive when it comes to how the containters you provide are built, is it possible goBGP has moved on slightly and your code is now doing something unexpected?

Any help appreciated,
Thanks

**Comment by dbarrosop** [comment]
They probably changed the API since a year ago. I'd suggest either updating the code in `add_path.py` or making sure you are running the gobgp version that was in "master" at the time of the blogpost.

**Comment by nzjc** [comment]
Thanks David, I'll try that!
